'use client';

import { FormFieldDefinition, FormFieldType } from '@/lib/types';

interface WorkflowFormFieldEditorProps {
  fields: FormFieldDefinition[];
  onChange: (fields: FormFieldDefinition[]) => void;
}

const FIELD_TYPES: { value: FormFieldType; label: string }[] = [
  { value: 'text', label: 'Text' },
  { value: 'textarea', label: 'Textarea' },
  { value: 'select', label: 'Select' },
  { value: 'multi_select', label: 'Multi Select' },
  { value: 'date', label: 'Date' },
  { value: 'user_picker', label: 'User Picker' },
  { value: 'channel_picker', label: 'Channel Picker' },
];

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

function inputClass() {
  return 'w-full rounded-lg border border-gray-700 bg-gray-900 px-3 py-2 text-white placeholder-gray-500 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500';
}

function labelClass() {
  return 'mb-1 block text-xs font-medium text-gray-400';
}

export default function WorkflowFormFieldEditor({ fields, onChange }: WorkflowFormFieldEditorProps) {
  function updateField(index: number, patch: Partial<FormFieldDefinition>) {
    const updated = fields.map((f, i) => (i === index ? { ...f, ...patch } : f));
    onChange(updated);
  }

  function removeField(index: number) {
    onChange(fields.filter((_, i) => i !== index));
  }

  function addField() {
    const newField: FormFieldDefinition = {
      label: '',
      name: '',
      type: 'text',
      required: false,
      placeholder: '',
    };
    onChange([...fields, newField]);
  }

  function handleLabelChange(index: number, label: string) {
    const current = fields[index];
    // Auto-generate name from label only if name was previously auto-generated or empty
    const wasAutoGenerated = current.name === '' || current.name === slugify(current.label);
    const patch: Partial<FormFieldDefinition> = { label };
    if (wasAutoGenerated) {
      patch.name = slugify(label);
    }
    updateField(index, patch);
  }

  function needsOptions(type: FormFieldType): boolean {
    return type === 'select' || type === 'multi_select';
  }

  return (
    <div className="space-y-3">
      {fields.map((field, index) => (
        <div key={index} className="rounded-lg border border-gray-700 bg-gray-800/50 p-3 space-y-2">
          {/* Header row with delete button */}
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-gray-300">Field {index + 1}</span>
            <button
              type="button"
              onClick={() => removeField(index)}
              className="rounded p-1 text-gray-500 hover:bg-gray-700 hover:text-red-400"
              title="Remove field"
              aria-label="Remove field"
            >
              <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Label and Name row */}
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className={labelClass()}>Label</label>
              <input
                type="text"
                className={inputClass()}
                placeholder="e.g. Full Name"
                value={field.label}
                onChange={(e) => handleLabelChange(index, e.target.value)}
              />
            </div>
            <div>
              <label className={labelClass()}>Name / Key</label>
              <input
                type="text"
                className={inputClass()}
                placeholder="e.g. full_name"
                value={field.name}
                onChange={(e) => updateField(index, { name: slugify(e.target.value) })}
              />
            </div>
          </div>

          {/* Type and Required row */}
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className={labelClass()}>Type</label>
              <select
                className={inputClass()}
                value={field.type}
                onChange={(e) => {
                  const newType = e.target.value as FormFieldType;
                  const patch: Partial<FormFieldDefinition> = { type: newType };
                  // Clear options when switching away from select types
                  if (!needsOptions(newType)) {
                    patch.options = undefined;
                  }
                  updateField(index, patch);
                }}
              >
                {FIELD_TYPES.map((ft) => (
                  <option key={ft.value} value={ft.value}>
                    {ft.label}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-end pb-2">
              <label className="flex items-center gap-2 text-sm text-gray-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={field.required ?? false}
                  onChange={(e) => updateField(index, { required: e.target.checked })}
                  className="h-4 w-4 rounded border-gray-600 bg-gray-900 text-blue-500 focus:ring-blue-500 focus:ring-offset-0"
                />
                Required
              </label>
            </div>
          </div>

          {/* Placeholder */}
          <div>
            <label className={labelClass()}>Placeholder</label>
            <input
              type="text"
              className={inputClass()}
              placeholder="Optional placeholder text"
              value={field.placeholder ?? ''}
              onChange={(e) => updateField(index, { placeholder: e.target.value || undefined })}
            />
          </div>

          {/* Options (only for select / multi_select) */}
          {needsOptions(field.type) && (
            <div>
              <label className={labelClass()}>Options (one per line)</label>
              <textarea
                className={inputClass()}
                rows={3}
                placeholder={'Option A\nOption B\nOption C'}
                value={(field.options ?? []).join('\n')}
                onChange={(e) => {
                  const lines = e.target.value.split('\n');
                  updateField(index, { options: lines });
                }}
              />
            </div>
          )}
        </div>
      ))}

      {/* Add field button */}
      <button
        type="button"
        onClick={addField}
        className="rounded-lg border border-dashed border-gray-600 px-3 py-2 text-sm text-gray-400 hover:border-gray-500 hover:text-gray-300 w-full"
      >
        + Add Field
      </button>
    </div>
  );
}
